data-path="/opt/besu/data"
genesis-file="/genesis/genesis-ibft.json"

p2p-host="0.0.0.0"
p2p-port=30303
max-peers=25

sync-mode="FULL"

miner-enabled=true
miner-coinbase="0xA64dFE27e652ee3A38f42888C2d570E39CA479E7"

logging="INFO"
